# Generated by Django 3.1.7 on 2021-04-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('cedula', models.IntegerField()),
                ('marca', models.CharField(max_length=120)),
                ('serie', models.CharField(max_length=120)),
                ('tensor', models.IntegerField()),
                ('conector_mecanico', models.IntegerField()),
                ('etiqueta', models.IntegerField()),
                ('cable', models.IntegerField()),
                ('amarras', models.IntegerField()),
                ('picotes', models.IntegerField()),
            ],
        ),
    ]
